#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IMAGE="uboot-marvell-builder"
DOCKERFILE="$SCRIPT_DIR/Dockerfile.build"
ORIG_BIN_HDR="$SCRIPT_DIR/orig_bin_hdr_raw.bin"
OUTPUT_ORIG="$SCRIPT_DIR/u-boot-with-orig-bin-hdr.bin"
OUTPUT_OWN="$SCRIPT_DIR/u-boot-wd.bin"

# Build container image if not exists
if ! podman image exists "$IMAGE"; then
    echo "==> Building container image..."
    podman build -t "$IMAGE" -f "$DOCKERFILE"
fi

# Clean up intermediate images before build to avoid doimage overwrite prompts
echo "==> Cleaning intermediate images..."
rm -f "$SCRIPT_DIR"/u-boot-a375-wd-spi.bin \
      "$SCRIPT_DIR"/u-boot-a375-wd-spi-debug.bin \
      "$SCRIPT_DIR"/u-boot-a375-wd-spi-uart.bin

# Build u-boot body + bin_hdr (bin_hdr compiled inside build.pl)
echo "==> Building U-Boot..."
podman run --rm -v "$SCRIPT_DIR:/build:Z" "$IMAGE" ./build.pl -f spi -b armada_375 -v wd "$@"

# Firmware 2: build.pl output with self-compiled bin_hdr (fixed name via -v wd)
echo "==> Packaging firmware 2: self-compiled bin_hdr (from build.pl output)..."
cp "$SCRIPT_DIR/u-boot-a375-wd-spi.bin" "$OUTPUT_OWN"
echo "==> Created: $OUTPUT_OWN"

# Remove intermediate images generated by build.pl
echo "==> Cleaning intermediate images..."
rm -f "$SCRIPT_DIR"/u-boot-a375-wd-spi.bin \
      "$SCRIPT_DIR"/u-boot-a375-wd-spi-debug.bin \
      "$SCRIPT_DIR"/u-boot-a375-wd-spi-uart.bin

DOIMAGE="$SCRIPT_DIR/tools/marvell/doimage"

# Firmware 1: original WD bin_hdr + our U-Boot body
echo "==> Packaging firmware 1: original WD bin_hdr..."
"$DOIMAGE" -T flash -D 0x0 -E 0x0 \
    -G "$ORIG_BIN_HDR" \
    "$SCRIPT_DIR/u-boot.bin" \
    "$OUTPUT_ORIG"
echo "==> Created: $OUTPUT_ORIG"

echo ""
echo "==> Build complete:"
echo "    $OUTPUT_ORIG  (original WD bin_hdr, stable)"
echo "    $OUTPUT_OWN   (self-compiled bin_hdr, updated DDR3 params)"
