#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IMAGE="uboot-marvell-builder"
DOCKERFILE="$SCRIPT_DIR/Dockerfile.build"
BIN_HDR="$SCRIPT_DIR/orig_bin_hdr_raw.bin"
OUTPUT="$SCRIPT_DIR/u-boot-wd.bin"

# Build container image if not exists
if ! podman image exists "$IMAGE"; then
    echo "==> Building container image..."
    podman build -t "$IMAGE" -f "$DOCKERFILE"
fi

# Build u-boot body
echo "==> Building U-Boot..."
podman run --rm -v "$SCRIPT_DIR:/build:Z" "$IMAGE" ./build.pl -f spi -b armada_375 "$@"

# Remove intermediate images generated by build.pl
echo "==> Cleaning intermediate images..."
rm -f "$SCRIPT_DIR"/u-boot-a375-*-spi.bin \
      "$SCRIPT_DIR"/u-boot-a375-*-spi-debug.bin \
      "$SCRIPT_DIR"/u-boot-a375-*-spi-uart.bin

# Repackage with original WD bin_hdr
echo "==> Packaging with original bin_hdr..."
"$SCRIPT_DIR/tools/marvell/doimage" -T flash -D 0x0 -E 0x0 \
    -G "$BIN_HDR" \
    "$SCRIPT_DIR/u-boot.bin" \
    "$OUTPUT"

echo "==> Done: $OUTPUT"
